version: '3.8'

services:
  express:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
