import 'dotenv/config';
import * as s from './schema/save';
export declare const db: import("drizzle-orm/node-postgres").NodePgDatabase<{
    cargoesToStations: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "cargo_to_stations";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "cargo_to_stations";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "cargo_to_stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            cargoId: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_id";
                tableName: "cargo_to_stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            stationId: import("drizzle-orm/pg-core").PgColumn<{
                name: "station_id";
                tableName: "cargo_to_stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            rating: import("drizzle-orm/pg-core").PgColumn<{
                name: "rating";
                tableName: "cargo_to_stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lastUpdated: import("drizzle-orm/pg-core").PgColumn<{
                name: "last_updated";
                tableName: "cargo_to_stations";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    cargoesToStationsRelations: import("drizzle-orm").Relations<"cargo_to_stations", {
        atStation: import("drizzle-orm").One<"stations", true>;
        cargoWaiting: import("drizzle-orm").One<"cargoes", true>;
    }>;
    cargoWaiting: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "cargoes_waiting";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            atStationId: import("drizzle-orm/pg-core").PgColumn<{
                name: "at_station_id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            fromStationId: import("drizzle-orm/pg-core").PgColumn<{
                name: "from_station_id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            viaStationId: import("drizzle-orm/pg-core").PgColumn<{
                name: "via_station_id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            cargoId: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_id";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            units: import("drizzle-orm/pg-core").PgColumn<{
                name: "units";
                tableName: "cargoes_waiting";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lastUpdated: import("drizzle-orm/pg-core").PgColumn<{
                name: "last_updated";
                tableName: "cargoes_waiting";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    cargoWaitingRelations: import("drizzle-orm").Relations<"cargoes_waiting", {
        cargoType: import("drizzle-orm").One<"cargoes", true>;
        cargoFromStationWaiting: import("drizzle-orm").One<"stations", true>;
        cargoViaStationWaiting: import("drizzle-orm").One<"stations", false>;
        cargoAtStationWaiting: import("drizzle-orm").One<"stations", true>;
    }>;
    towns: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "towns";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "towns";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "towns";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "towns";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            townId: import("drizzle-orm/pg-core").PgColumn<{
                name: "town_id";
                tableName: "towns";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            population: import("drizzle-orm/pg-core").PgColumn<{
                name: "population";
                tableName: "towns";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isCity: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_city";
                tableName: "towns";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            x: import("drizzle-orm/pg-core").PgColumn<{
                name: "x";
                tableName: "towns";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            y: import("drizzle-orm/pg-core").PgColumn<{
                name: "y";
                tableName: "towns";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    stations: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "stations";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "stations";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "stations";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            stationId: import("drizzle-orm/pg-core").PgColumn<{
                name: "station_id";
                tableName: "stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            companyId: import("drizzle-orm/pg-core").PgColumn<{
                name: "company_id";
                tableName: "stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasTrain: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_train";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasTruck: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_truck";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasBus: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_bus";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasAirport: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_airport";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasDock: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_dock";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasAny: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_any";
                tableName: "stations";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            x: import("drizzle-orm/pg-core").PgColumn<{
                name: "x";
                tableName: "stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            y: import("drizzle-orm/pg-core").PgColumn<{
                name: "y";
                tableName: "stations";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    stationRelations: import("drizzle-orm").Relations<"stations", {
        owner: import("drizzle-orm").One<"companies", true>;
        cargoStatistics: import("drizzle-orm").Many<"cargo_to_stations">;
    }>;
    signs: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "signs";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "signs";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isInGame: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_in_game";
                tableName: "signs";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: false;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            signId: import("drizzle-orm/pg-core").PgColumn<{
                name: "sign_id";
                tableName: "signs";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "signs";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            text: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "signs";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            x: import("drizzle-orm/pg-core").PgColumn<{
                name: "x";
                tableName: "signs";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            y: import("drizzle-orm/pg-core").PgColumn<{
                name: "y";
                tableName: "signs";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    signsRelations: import("drizzle-orm").Relations<"signs", {
        cargoesToSave: import("drizzle-orm").One<"saves", true>;
    }>;
    CargoPaymentModel: typeof s.CargoPaymentModel;
    cargoPaymentModelEnum: import("drizzle-orm/pg-core").PgEnum<[s.CargoPaymentModel]>;
    saves: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "saves";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "saves";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            serverName: import("drizzle-orm/pg-core").PgColumn<{
                name: "server_name";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            gameVersion: import("drizzle-orm/pg-core").PgColumn<{
                name: "game_version";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            dedicatedFlag: import("drizzle-orm/pg-core").PgColumn<{
                name: "dedicated_flag";
                tableName: "saves";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            mapName: import("drizzle-orm/pg-core").PgColumn<{
                name: "map_name";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            mapSeed: import("drizzle-orm/pg-core").PgColumn<{
                name: "map_seed";
                tableName: "saves";
                dataType: "number";
                columnType: "PgBigInt53";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            landscape: import("drizzle-orm/pg-core").PgColumn<{
                name: "landscape";
                tableName: "saves";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            startDate: import("drizzle-orm/pg-core").PgColumn<{
                name: "start_date";
                tableName: "saves";
                dataType: "number";
                columnType: "PgBigInt53";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            mapWidth: import("drizzle-orm/pg-core").PgColumn<{
                name: "map_width";
                tableName: "saves";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            mapHeight: import("drizzle-orm/pg-core").PgColumn<{
                name: "map_height";
                tableName: "saves";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryPack: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_pack";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            industryVersion: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_version";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            industryEconomy: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_economy";
                tableName: "saves";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            timeFetchedCargos: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_cargos";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedIndustryTypes: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_industry_types";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedIndustries: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_industries";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedStations: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_stations";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedMonthlyStats: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_monthly_stats";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedCompanies: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_companies";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            timeFetchedTowns: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_towns";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            cargoPaymentModel: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_payment_model";
                tableName: "saves";
                dataType: "string";
                columnType: "PgEnumColumn";
                data: s.CargoPaymentModel;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [s.CargoPaymentModel];
                baseColumn: never;
            }, {}, {}>;
            timeFetchedCargoWaiting: import("drizzle-orm/pg-core").PgColumn<{
                name: "time_fetched_cargo_waiting";
                tableName: "saves";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    savesRelations: import("drizzle-orm").Relations<"saves", {
        companies: import("drizzle-orm").Many<"companies">;
        industryTypes: import("drizzle-orm").Many<"industry_types">;
        cargoes: import("drizzle-orm").Many<"cargoes">;
        circles: import("drizzle-orm").Many<"circles">;
    }>;
    monthlyStats: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "monthly_stats";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            year: import("drizzle-orm/pg-core").PgColumn<{
                name: "year";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            month: import("drizzle-orm/pg-core").PgColumn<{
                name: "month";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryId: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_id";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            cargoId: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_id";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            stockpiledCargo: import("drizzle-orm/pg-core").PgColumn<{
                name: "stockpiled_cargo";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lastMonthProduction: import("drizzle-orm/pg-core").PgColumn<{
                name: "last_month_production";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lastMonthTransported: import("drizzle-orm/pg-core").PgColumn<{
                name: "last_month_transported";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lastMonthTransportedPercentage: import("drizzle-orm/pg-core").PgColumn<{
                name: "last_month_transported_percentage";
                tableName: "monthly_stats";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    industries: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "industries";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "industries";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryId: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_id";
                tableName: "industries";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "industries";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            constructionDate: import("drizzle-orm/pg-core").PgColumn<{
                name: "construction_date";
                tableName: "industries";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryTypeId: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_type_id";
                tableName: "industries";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            x: import("drizzle-orm/pg-core").PgColumn<{
                name: "x";
                tableName: "industries";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            y: import("drizzle-orm/pg-core").PgColumn<{
                name: "y";
                tableName: "industries";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    industriesRelations: import("drizzle-orm").Relations<"industries", {
        type: import("drizzle-orm").One<"industry_types", true>;
    }>;
    industryTypes: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "industry_types";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "industry_types";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryTypeId: import("drizzle-orm/pg-core").PgColumn<{
                name: "industry_type_id";
                tableName: "industry_types";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "industry_types";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "industry_types";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            hasHeliport: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_heliport";
                tableName: "industry_types";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hasDock: import("drizzle-orm/pg-core").PgColumn<{
                name: "has_dock";
                tableName: "industry_types";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            hex: import("drizzle-orm/pg-core").PgColumn<{
                name: "hex";
                tableName: "industry_types";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    industryTypesRelation: import("drizzle-orm").Relations<"industry_types", {
        cargoesToIndustryTypes: import("drizzle-orm").Many<"cargos_to_industry_types">;
        industries: import("drizzle-orm").Many<"industries">;
        industryTypesToSave: import("drizzle-orm").One<"saves", true>;
    }>;
    circleTypeEnum: import("drizzle-orm/pg-core").PgEnum<["manhattan", "euclidean"]>;
    circles: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "circles";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "circles";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "circles";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            text: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "circles";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            x: import("drizzle-orm/pg-core").PgColumn<{
                name: "x";
                tableName: "circles";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            y: import("drizzle-orm/pg-core").PgColumn<{
                name: "y";
                tableName: "circles";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            radius: import("drizzle-orm/pg-core").PgColumn<{
                name: "radius";
                tableName: "circles";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            color: import("drizzle-orm/pg-core").PgColumn<{
                name: "color";
                tableName: "circles";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            circleType: import("drizzle-orm/pg-core").PgColumn<{
                name: "circle_type";
                tableName: "circles";
                dataType: "string";
                columnType: "PgEnumColumn";
                data: "manhattan" | "euclidean";
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: ["manhattan", "euclidean"];
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    circlesRelations: import("drizzle-orm").Relations<"circles", {
        save: import("drizzle-orm").One<"saves", true>;
    }>;
    cargoes: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "cargoes";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            cargoId: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_id";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "cargoes";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            label: import("drizzle-orm/pg-core").PgColumn<{
                name: "label";
                tableName: "cargoes";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            weight: import("drizzle-orm/pg-core").PgColumn<{
                name: "weight";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            value: import("drizzle-orm/pg-core").PgColumn<{
                name: "value";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isPassenger: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_passenger";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: false;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isMail: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_mail";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isExpress: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_express";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isArmoured: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_armoured";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isBulk: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_bulk";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isPieceGoods: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_piece_goods";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isLiquid: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_liquid";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isRefrigerated: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_refrigerated";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isCovered: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_covered";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isHazardous: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_hazardous";
                tableName: "cargoes";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            townEffect: import("drizzle-orm/pg-core").PgColumn<{
                name: "town_effect";
                tableName: "cargoes";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            grfData: import("drizzle-orm/pg-core").PgColumn<{
                name: "grf_data";
                tableName: "cargoes";
                dataType: "json";
                columnType: "PgJsonb";
                data: unknown;
                driverParam: unknown;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    cargoesRelations: import("drizzle-orm").Relations<"cargoes", {
        cargoesToIndustryTypes: import("drizzle-orm").Many<"cargos_to_industry_types">;
        cargoesToStations: import("drizzle-orm").Many<"cargo_to_stations">;
        cargoesToSave: import("drizzle-orm").One<"saves", true>;
    }>;
    companies: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "companies";
        schema: undefined;
        columns: {
            id: import("drizzle-orm/pg-core").PgColumn<{
                name: "id";
                tableName: "companies";
                dataType: "number";
                columnType: "PgSerial";
                data: number;
                driverParam: number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            companyId: import("drizzle-orm/pg-core").PgColumn<{
                name: "company_id";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            saveId: import("drizzle-orm/pg-core").PgColumn<{
                name: "save_id";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            name: import("drizzle-orm/pg-core").PgColumn<{
                name: "name";
                tableName: "companies";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            managerName: import("drizzle-orm/pg-core").PgColumn<{
                name: "manager_name";
                tableName: "companies";
                dataType: "string";
                columnType: "PgVarchar";
                data: string;
                driverParam: string;
                notNull: true;
                hasDefault: true;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, {}, {}>;
            color: import("drizzle-orm/pg-core").PgColumn<{
                name: "color";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            startDate: import("drizzle-orm/pg-core").PgColumn<{
                name: "start_date";
                tableName: "companies";
                dataType: "date";
                columnType: "PgDate";
                data: Date;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            isAI: import("drizzle-orm/pg-core").PgColumn<{
                name: "is_ai";
                tableName: "companies";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: false;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            trains: import("drizzle-orm/pg-core").PgColumn<{
                name: "trains";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lorries: import("drizzle-orm/pg-core").PgColumn<{
                name: "lorries";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            buses: import("drizzle-orm/pg-core").PgColumn<{
                name: "buses";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            planes: import("drizzle-orm/pg-core").PgColumn<{
                name: "planes";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            ships: import("drizzle-orm/pg-core").PgColumn<{
                name: "ships";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            trainStations: import("drizzle-orm/pg-core").PgColumn<{
                name: "train_stations";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            lorryStations: import("drizzle-orm/pg-core").PgColumn<{
                name: "lorry_stations";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            busStations: import("drizzle-orm/pg-core").PgColumn<{
                name: "bus_stations";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            airports: import("drizzle-orm/pg-core").PgColumn<{
                name: "airports";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            harbors: import("drizzle-orm/pg-core").PgColumn<{
                name: "harbors";
                tableName: "companies";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: true;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    companiesRelations: import("drizzle-orm").Relations<"companies", {
        type: import("drizzle-orm").One<"saves", true>;
        ownedStations: import("drizzle-orm").Many<"stations">;
    }>;
    cargoesToIndustryTypes: import("drizzle-orm/pg-core").PgTableWithColumns<{
        name: "cargos_to_industry_types";
        schema: undefined;
        columns: {
            cargoId: import("drizzle-orm/pg-core").PgColumn<{
                name: "cargo_id";
                tableName: "cargos_to_industry_types";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            industryTypeId: import("drizzle-orm/pg-core").PgColumn<{
                name: "industrytype_id";
                tableName: "cargos_to_industry_types";
                dataType: "number";
                columnType: "PgInteger";
                data: number;
                driverParam: string | number;
                notNull: true;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
            accepts: import("drizzle-orm/pg-core").PgColumn<{
                name: "accepts";
                tableName: "cargos_to_industry_types";
                dataType: "boolean";
                columnType: "PgBoolean";
                data: boolean;
                driverParam: boolean;
                notNull: false;
                hasDefault: false;
                enumValues: undefined;
                baseColumn: never;
            }, {}, {}>;
        };
        dialect: "pg";
    }>;
    cargoesToIndustryTypesRelations: import("drizzle-orm").Relations<"cargos_to_industry_types", {
        industryType: import("drizzle-orm").One<"industry_types", true>;
        cargo: import("drizzle-orm").One<"cargoes", true>;
    }>;
}>;
